# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Validate py312 with black
        run: |
          black --target-version=py312 ./gpq.py
      - name: Write Release Body
        run: iex "echo `"${{ github.event.head_commit.message }}`" | Tee-Object RELEASE_BODY"
      - name: Build app & zip
        run: |
          pyinstaller gpq.py
          cp members.json.example dist/gpq
          mkdir "dist/gpq/scores"
          cd dist
          mv gpq gpq-${{ github.sha }}
          Compress-Archive -Path gpq-${{ github.sha }} -DestinationPath ../gpq-${{ github.ref_name }}.zip
          cd ..
      - name: Release
        if: ${{ env.ACT != '' && startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: gpq-${{ github.ref_name }}.zip
          generate_release_notes: true
          fail_on_unmatched_files: true
